version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb-dev"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  mongo-seed-users:
    image: mongo:latest
    volumes:
      - ./seed-data:/seed-data
    command:
      'bash -c "mongoimport --host mongodb-dev --db elt --collection users --type json --file /seed-data/users.json --jsonArray"'