apiVersion: v1
kind: Service
metadata:
  namespace: api
  labels:
    app: elt-auth
  name: elt-auth
spec:
  type: LoadBalancer
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP
  selector:
    app: elt-auth